#use_frameworks!

platform :ios, '9.0'

target 'easydebug_Example' do
#  pod 'easydebug', :path => '../'
  pod 'AFNetworking'
#  pod 'PLCrashReporter'
  pod 'GCDWebServer/WebUploader'

  target 'easydebug_Tests' do
    inherit! :search_paths

    
  end
end
